FORMAT: 1A
HOST: https://api.ciscospark.com/v1/

# Organizations

A set of people in Webex Teams. Organizations may manage other organizations or be managed themselves. This organizations resource can be accessed only by an admin.

## Organizations Collection [/organizations]

### List Organizations [GET /organizations]

List all organizations visible by your account. The results will not be [paginated](/docs/teams/api/basics#pagination).

+ Request

    + Headers

            Authorization: Bearer YOUR_AUTHORIZATION_TOKEN

+ Response 200 (application/json)

    + Attributes (Organization Collection Response)

### Get Organization Details [GET /organizations/{orgId}]

Shows details for an organization, by ID.

Specify the org ID in the `orgId` parameter in the URI.

+ Request

    + Headers

            Authorization: Bearer YOUR_AUTHORIZATION_TOKEN

+ Parameters

    + orgId: `Y2lzY29zcGFyazovL3VzL09SR0FOSVpBVElPTi85NmFiYzJhYS0zZGNjLTExZTUtYTE1Mi1mZTM0ODE5Y2RjOWE` (string, required) - The unique identifier for the organization.

+ Response 200 (application/json)

    + Attributes (Organization)

# Data Structures

## Organization (object)

+ id: `Y2lzY29zcGFyazovL3VzL09SR0FOSVpBVElPTi85NmFiYzJhYS0zZGNjLTExZTUtYTE1Mi1mZTM0ODE5Y2RjOWE` (string) - A unique identifier for the organization.
+ displayName: `Acme, Inc.` (string) - Full name of the organization.
+ created: `2015-10-18T14:26:16+00:00` (string) - The date and time the organization was created.

## Organization Collection Response (object)

+ items (array[Organization])